# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c619f41e46de2c648c82852de117d90f4b22d8cefb6b2ee1f132a5dccae5690a7fa0f797c87ab7789d190f9d0fdb2d291a68b4af993a78f337f837cefbea19f

test:
  secret_key_base: 67db6253518c75717ec0fbec601982933aa759865d1f8afb1669abe9175d2ea131b4fa1a1c98c024e01d10a9bb58217cf399c31671cfe4d6dbacf75162f15908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
